/**
 * Duke Data Service API.
 * REST API to the Duke Data Service. Some requests require Authentication.
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DukeDataServiceApi) {
      root.DukeDataServiceApi = {};
    }
    root.DukeDataServiceApi.ProjecttransfersApi = factory(root.DukeDataServiceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Projecttransfers service.
   * @module api/ProjecttransfersApi
   * @version 0.0.2
   */

  /**
   * Constructs a new ProjecttransfersApi. 
   * @alias module:api/ProjecttransfersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getApiV1ProjectTransfers operation.
     * @callback module:api/ProjecttransfersApi~getApiV1ProjectTransfersCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View all project transfers
     * View all project transfers  View all project transfers.
     * @param {Object} opts Optional parameters
     * @param {module:model/String} opts.status Status must be one of the allowed statuses
     * @param {module:api/ProjecttransfersApi~getApiV1ProjectTransfersCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getApiV1ProjectTransfers = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'status': opts['status']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/project_transfers', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiV1ProjectTransfersId operation.
     * @callback module:api/ProjecttransfersApi~getApiV1ProjectTransfersIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View a project transfer
     * View a project transfer  Used to view an instance of a project transfer.
     * @param {Integer} id 
     * @param {module:api/ProjecttransfersApi~getApiV1ProjectTransfersIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getApiV1ProjectTransfersId = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getApiV1ProjectTransfersId";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/project_transfers/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putApiV1ProjectTransfersIdAccept operation.
     * @callback module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdAcceptCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Accept a project transfer
     * Accept a project transfer  Accept a pending project transfer.
     * @param {String} id The unique id of the project transfer.
     * @param {Object} opts Optional parameters
     * @param {String} opts.statusComment An optional comment that can be provided.
     * @param {module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdAcceptCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putApiV1ProjectTransfersIdAccept = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling putApiV1ProjectTransfersIdAccept";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'status_comment': opts['statusComment']
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/project_transfers/{id}/accept', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putApiV1ProjectTransfersIdCancel operation.
     * @callback module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdCancelCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Cancel a project transfer
     * Cancel a project transfer  Cancel a pending project transfer.
     * @param {String} id The unique id of the project transfer.
     * @param {Object} opts Optional parameters
     * @param {String} opts.statusComment An optional comment that can be provided.
     * @param {module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdCancelCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putApiV1ProjectTransfersIdCancel = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling putApiV1ProjectTransfersIdCancel";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'status_comment': opts['statusComment']
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/project_transfers/{id}/cancel', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the putApiV1ProjectTransfersIdReject operation.
     * @callback module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdRejectCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Reject a project transfer
     * Reject a project transfer  Reject a pending project transfer.
     * @param {String} id The unique id of the project transfer.
     * @param {Object} opts Optional parameters
     * @param {String} opts.statusComment An optional comment that can be provided.
     * @param {module:api/ProjecttransfersApi~putApiV1ProjectTransfersIdRejectCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.putApiV1ProjectTransfersIdReject = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling putApiV1ProjectTransfersIdReject";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'status_comment': opts['statusComment']
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/project_transfers/{id}/reject', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
