/**
 * Duke Data Service API.
 * REST API to the Duke Data Service. Some requests require Authentication.
 *
 * OpenAPI spec version: 0.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.DukeDataServiceApi) {
      root.DukeDataServiceApi = {};
    }
    root.DukeDataServiceApi.TagsApi = factory(root.DukeDataServiceApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * Tags service.
   * @module api/TagsApi
   * @version 0.0.2
   */

  /**
   * Constructs a new TagsApi. 
   * @alias module:api/TagsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the deleteApiV1TagsId operation.
     * @callback module:api/TagsApi~deleteApiV1TagsIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a tag
     * Delete a tag  Deletes the tag
     * @param {Integer} id 
     * @param {module:api/TagsApi~deleteApiV1TagsIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.deleteApiV1TagsId = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteApiV1TagsId";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiV1TagsId operation.
     * @callback module:api/TagsApi~getApiV1TagsIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * View tag
     * View tag  view tag
     * @param {Integer} id 
     * @param {module:api/TagsApi~getApiV1TagsIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getApiV1TagsId = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getApiV1TagsId";
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiV1TagsLabels operation.
     * @callback module:api/TagsApi~getApiV1TagsLabelsCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List tag labels
     * List tag labels  Get a list of the distinct tag label values visible to the current user.
     * @param {Object} opts Optional parameters
     * @param {String} opts.objectKind Restricts search scope to tags for this kind of object
     * @param {String} opts.labelContains Searches for tags that contain this text fragment
     * @param {module:api/TagsApi~getApiV1TagsLabelsCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getApiV1TagsLabels = function(opts, callback) {
      opts = opts || {};
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
        'object_kind': opts['objectKind'],
        'label_contains': opts['labelContains']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/labels', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getApiV1TagsObjectKindObjectId operation.
     * @callback module:api/TagsApi~getApiV1TagsObjectKindObjectIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List tag objects
     * List tag objects  Lists tag objects for which the current user has the \&quot;view_project\&quot; permission.
     * @param {Integer} objectKind 
     * @param {Integer} objectId 
     * @param {module:api/TagsApi~getApiV1TagsObjectKindObjectIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.getApiV1TagsObjectKindObjectId = function(objectKind, objectId, callback) {
      var postBody = null;

      // verify the required parameter 'objectKind' is set
      if (objectKind == undefined || objectKind == null) {
        throw "Missing the required parameter 'objectKind' when calling getApiV1TagsObjectKindObjectId";
      }

      // verify the required parameter 'objectId' is set
      if (objectId == undefined || objectId == null) {
        throw "Missing the required parameter 'objectId' when calling getApiV1TagsObjectKindObjectId";
      }


      var pathParams = {
        'object_kind': objectKind,
        'object_id': objectId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = [];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/{object_kind}/{object_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postApiV1TagsObjectKindObjectId operation.
     * @callback module:api/TagsApi~postApiV1TagsObjectKindObjectIdCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create object tag
     * Create object tag  Creates an object tag.
     * @param {String} label 
     * @param {Integer} objectKind 
     * @param {Integer} objectId 
     * @param {module:api/TagsApi~postApiV1TagsObjectKindObjectIdCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.postApiV1TagsObjectKindObjectId = function(label, objectKind, objectId, callback) {
      var postBody = null;

      // verify the required parameter 'label' is set
      if (label == undefined || label == null) {
        throw "Missing the required parameter 'label' when calling postApiV1TagsObjectKindObjectId";
      }

      // verify the required parameter 'objectKind' is set
      if (objectKind == undefined || objectKind == null) {
        throw "Missing the required parameter 'objectKind' when calling postApiV1TagsObjectKindObjectId";
      }

      // verify the required parameter 'objectId' is set
      if (objectId == undefined || objectId == null) {
        throw "Missing the required parameter 'objectId' when calling postApiV1TagsObjectKindObjectId";
      }


      var pathParams = {
        'object_kind': objectKind,
        'object_id': objectId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'label': label
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/{object_kind}/{object_id}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the postApiV1TagsObjectKindObjectIdAppend operation.
     * @callback module:api/TagsApi~postApiV1TagsObjectKindObjectIdAppendCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Append a list of object tags
     * Append a list of object tags  Append a list of tags to an object.
     * @param {Array.<String>} tagsLabel The textual tag content
     * @param {Integer} objectKind 
     * @param {Integer} objectId 
     * @param {module:api/TagsApi~postApiV1TagsObjectKindObjectIdAppendCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.postApiV1TagsObjectKindObjectIdAppend = function(tagsLabel, objectKind, objectId, callback) {
      var postBody = null;

      // verify the required parameter 'tagsLabel' is set
      if (tagsLabel == undefined || tagsLabel == null) {
        throw "Missing the required parameter 'tagsLabel' when calling postApiV1TagsObjectKindObjectIdAppend";
      }

      // verify the required parameter 'objectKind' is set
      if (objectKind == undefined || objectKind == null) {
        throw "Missing the required parameter 'objectKind' when calling postApiV1TagsObjectKindObjectIdAppend";
      }

      // verify the required parameter 'objectId' is set
      if (objectId == undefined || objectId == null) {
        throw "Missing the required parameter 'objectId' when calling postApiV1TagsObjectKindObjectIdAppend";
      }


      var pathParams = {
        'object_kind': objectKind,
        'object_id': objectId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
        'tags[][label]': this.apiClient.buildCollectionParam(tagsLabel, 'csv')
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/api/v1/tags/{object_kind}/{object_id}/append', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
